### ISSUE TITLE
Your development environment information still remains

### ISSUE THREAD

**Issue by kaosf** [dwrap/cli#6]
I checked it on Ubuntu 16.04 amd64.

``` sh
# Prerequisites
wget https://github.com/dwrap/cli/releases/download/v0.0.1/dwrap_linux-amd64.zip
sudo apt install unzip
unzip dwrap_linux-amd64.zip

# Run dwrap
./dwrap
```

An error occured like following:

```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x87c840, 0xc82000a110)
        /Users/<Maybe your name>/.homebrew/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
main.main()
        /<maybe>/<your>/<working>/<directory>/dwrap/cli/cmd/main.go:30 +0xed4
```

FYI, the same error occured with dwrap_linux-386.zip and the same information was displayed.

**Comment by yamamoto-febc** [comment]
@kaosf It looks like build environment problem. 
So I updated the build essentials and replaced release binaries by 0d6afc1b389da0e5208d6096cb436534c58115ca.

And validate of commandline argument was incorrect.
It was fixed by ef60912a2334f56c259b26cd12bec8bcef12426a.

Thank you for your contribution‼️
